### ISSUE TITLE
Admob Crash: Parameter must be a descendant of this view

### ISSUE THREAD

**Issue by gollobo** [googleads/googleads-mobile-unity#2353]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.11f1 2021.3.12f1
  * Google Mobile Ads Unity plugin version: v7.3.0
  * Platform: Android
  * Platform OS version: 12, 11, 10
  * Any specific devices issue occurs on: Multiple devices
  * Mediation ad networks used, and their versions: None

### [REQUIRED] Step 2: Describe the problem

After several months after having integrated this Admob plugin, we are getting mostly in Android 11 but also Android 10 and 12 a lot crashes of the type:

`Exception java.lang.Error: FATAL EXCEPTION
Caused by: java.lang.IllegalArgumentException: parameter must be a descendant of this view`

After researching the error and searching online, not only occurs in Unity, but also in other Admob plugins (React Native, etc.) According to forums one solution could be to add "AdView.setDescendantFocusability(ViewGroup.FOCUS_BLOCK_DESCENDANTS)" to the Banner Adview, but from this plugin there is no access to the native Android code

#### Steps to reproduce:

Use the app normally with a banner enabled

#### Relevant Code:
Crash example:

```
Exception java.lang.Error: FATAL EXCEPTION [main]
Unity version     : 2021.3.11f1
Device model      : Xiaomi M2101K7BL
Build Type        : Release
Scripting Backend : IL2CPP
ABI               : arm64-v8a
Strip Engine Code : true

Caused by: java.lang.IllegalArgumentException: parameter must be a descendant of this view
  at android.view.ViewGroup.offsetRectBetweenParentAndChild (ViewGroup.java:6415)
  at android.view.ViewGroup.offsetDescendantRectToMyCoords (ViewGroup.java:6341)
  at android.view.ViewRootImpl.scrollToRectOrFocus (ViewRootImpl.java:4693)
  at android.view.ViewRootImpl.draw (ViewRootImpl.java:4229)
  at android.view.ViewRootImpl.performDraw (ViewRootImpl.java:4073)
  at android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:3331)
  at android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:2131)
  at android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:8605)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:976)
  at android.view.Choreographer.doCallbacks (Choreographer.java:799)
  at android.view.Choreographer.doFrame (Choreographer.java:734)
  at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:961)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:236)
  at android.app.ActivityThread.main (ActivityThread.java:8031)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:620)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1011)
```

**Comment by gollobo** [comment]
Link to the Unity forum with more users with the same crashes with the Admob plugin:
[Forum Unity](https://forum.unity.com/threads/android-crash-on-unity-2019-4-26f.1116979/page-2)

**Comment by shefich** [comment]
Also have too many such crashes.
Unity 2020.3.38,  2020.3.39, 2020.3.40, 2020.3.41.
Google Mobile Ads Unity plugin version: v7.1.0, 7.2.0.

**Comment by NVentimiglia** [comment]
@gollobo 

Can you provide a sample project or sure fire steps which demonstrates this problem, I am unable to replicate this problem in 7.2.0 on an Android 12 emulator. I will need this in order to verify the fix.

**Comment by gollobo** [comment]
@NVentimiglia thanks for your reply!

I tried to reproduce the crash on my devices, but I haven’t been able, it seems a crash on random devices. This is a simplified version of my AdManager.cs. NOTE: I have tried in production with and without Invoke delay.

    void Start()
    {
        Invoke("InitializeAdMob", 1F);
    }

    public void InitializeAdMob()
    {
        MobileAds.Initialize(initStatus => { });
        Invoke("InitBanner", 1F);
    }

    public void InitBanner()
    {

        if (this.bannerView != null)
        {
            this.bannerView.Destroy();
        }

        AdSize adaptiveSize =
                 AdSize.GetCurrentOrientationAnchoredAdaptiveBannerAdSizeWithWidth(AdSize.FullWidth);
        this.bannerView = new BannerView(adUnitId, adaptiveSize, AdPosition.Bottom);

        AdRequest request = new AdRequest.Builder().Build();
        bannerView.LoadAd(request);

    }

**Comment by Mecze** [comment]
Hello, 

We are affected too by this issue.
We also cannot reproduce it.

I see a change on Banner.java made yesterday
When will it released?

Thanks

**Comment by NVentimiglia** [comment]
> the crash on my devices, but I haven’t been able, it seems a crash on random devices. This is a simplified version of my AdManage

That is an experiment where I am trying to replicate the issue. No date on the release.

@shefich @Mecze @gollobo @dberlin 

I reason this might be caused by a creative. Do any of you have a charles / network log of the defective banner? An ad request will also help.

**Comment by Raxman1** [comment]
android.app.PendingIntent.checkFlags java.lang.Error . Such an error when I publish the application in the Google Play Console. When I use the test apk on the emulator, everything is ok, when I download from the Play Store it crashes after 5 seconds.

**Comment by Svoyi** [comment]
android.app.PendingIntent.checkFlags java.lang.Error . Such an error when I publish the application in the Google Play Console. When I use the test apk on the emulator, everything is ok, when I download from the Play Store it crashes after 5 seconds. We found that the error is mainly on Samsung with andoid 12

**Comment by Hamid0019** [comment]
@NVentimiglia  Any solution of this crash?
We are getting too many.

**Comment by gollobo** [comment]
Can setDescendantFocusability(ViewGroup.FOCUS_BLOCK_DESCENDANTS) be added as an optional flag when you create the bannerView? So only developers with this crash can test if it works

**Comment by gollobo** [comment]
To add more information to this error:
- The error continues to occur in the versions of Unity 2021.3.13f and 2021.3.14f
- Tested on plugin versions 7.1.0, 7.2.0, 7.3.0, 7.3.1
- Android 11 and 12 and set to SDK 31 in Unity
- Occurs when a banner is enabled
- We tested with different Banner sizes (SmartBanner, FullWidthAdaptativeBanner)
- We have tested with start and ad load optimizations
- Our games are distributed to thousands of players all over the world, so it is difficult to know which advertising makes the crash
- We have tried to switch to Native Ads to use our own Banners, but they seem to be broken in this plugin too

@NVentimiglia is there any news on this? Currently is the +35% of crash rates in ALL our Unity games, and we don’t want to change to another ad provider.

**Comment by mhctseu** [comment]
Hi, we are affected by this issue too. Below is our SDK version:
Unity: 2020.3.38f1c2
Google Mobile Ads Unity Plugin: 7.2.0
Google Mobile Ads Android SDK: 21.0.0

Any update on this issue?

**Comment by companyworkahmad** [comment]
Is there any solution?

**Comment by umairmanz** [comment]
I recently updated Google Mobile Ads Unity Plugin: 7.3.1 in our game got the same crash issue

Exception java.lang.Error: FATAL EXCEPTION [main]
Unity version     : 2020.3.38f1
Device model      : INFINIX MOBILITY LIMITED Infinix X652A
Device fingerprint: Infinix/H628/Infinix-X652A:9/PPR1.180610.011/LK-210831V178:user/release-keys
Build Type        : Release
Scripting Backend : IL2CPP
ABI               : arm64-v8a
Strip Engine Code : true

Caused by: java.lang.IllegalArgumentException: parameter must be a descendant of this view
  at android.view.ViewGroup.offsetRectBetweenParentAndChild (ViewGroup.java:6186)
  at android.view.ViewGroup.offsetDescendantRectToMyCoords (ViewGroup.java:6111)
  at android.view.ViewRootImpl.scrollToRectOrFocus (ViewRootImpl.java:3800)
  at android.view.ViewRootImpl.draw (ViewRootImpl.java:3371)
  at android.view.ViewRootImpl.performDraw (ViewRootImpl.java:3296)
  at android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:2650)
  at android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:1560)
  at android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:7514)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:977)
  at android.view.Choreographer.doCallbacks (Choreographer.java:785)
  at android.view.Choreographer.doFrame (Choreographer.java:717)
  at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:963)
  at android.os.Handler.handleCallback (Handler.java:873)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:193)
  at android.app.ActivityThread.main (ActivityThread.java:6819)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:497)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:912)

**Comment by Haseebahmed71** [comment]
as issues in fixed as mentioned in the above thread. When will expect to get that fix in Google Mobile Ads Unity plugin

**Comment by NVentimiglia** [comment]
Hi,

Thanks for the reminder. I have pushed for the fix for this issue to be released. b/270246759

**Comment by FeliceCasa** [comment]
> issue is fixed as mentioned in the above thread. When will expect to get that fix in Google Mobile Ads Unity plugin
Can you tell me what method you used to fix this issue? I cannot find any solution in the above messages. Thanks a lot.
@Haseebahmed71

**Comment by Haseebahmed71** [comment]
> @gollobo
> 
> Can you provide a sample project or sure fire steps which demonstrates this problem, I am unable to replicate this problem in 7.2.0 on an Android 12 emulator. I will need this in order to verify the fix.

@FeliceCasa the issue is fixed with banner.java class as mentioned in this message.

**Comment by FeliceCasa** [comment]
@Haseebahmed71 Thank you very much for your reply! I got it. But unfortunately, this fix was not included in the latest version 7.4.1. It seems we will need to wait for the next release to fix this.

**Comment by billyhct** [comment]
> > @gollobo
> > Can you provide a sample project or sure fire steps which demonstrates this problem, I am unable to replicate this problem in 7.2.0 on an Android 12 emulator. I will need this in order to verify the fix.
> 
> @FeliceCasa the issue is fixed with banner.java class as mentioned in this message.

We received a lot of errors:
android.view.ViewGroup.offsetRectBetweenParentAndChild
java.lang.Error

It's difficult to replicate as this is reported by Google Play Console only with around 1% from specific devices.
We "guess" this may be triggered when the banner was there and triggered another rewarded ads/Interstitial ads, this crash may have higher chance to occur.

**Comment by DmitryPtukhin** [comment]
With this crash, we exceed the Bad behavior threshold. Therefore, we cannot release an update. Terrible!

**Comment by madnesslabo** [comment]
This error didn't solve in Google Mobile Ads Unity Plugin v8.0.0 .I get the same error.
The crash rate exceeds the threshold set by Google.
Will it take a long time to resolve? Should I downgrade the plugin?

**Comment by mhctseu** [comment]
> This error didn't solve in Google Mobile Ads Unity Plugin v8.0.0 .I get the same error. The crash rate exceeds the threshold set by Google. Will it take a long time to resolve? Should I downgrade the plugin?

Oh no, I thought with the release of  v8.0.0 which includes this commit (f90ced66431220d4ad2d5d903889cd1342e3cff4), this issue should have been fixed...

**Comment by gollobo** [comment]
> Oh no, I thought with the release of v8.0.0 which includes this commit ([f90ced6](https://github.com/googleads/googleads-mobile-unity/commit/f90ced66431220d4ad2d5d903889cd1342e3cff4)), this issue should have been fixed...

The commit with the fix was a test that includes:
`AdView.setDescendantFocusability(ViewGroup.FOCUS_BLOCK_DESCENDANTS)`

But never was included in the main branch, i dont know why.

**Comment by MuhammadWaqasOfficial** [comment]
Got same crash as well. They said it was fixed. but still exists in 7.4.1, don't know if exists in 8.0.0 or not.

Exception java.lang.Error: FATAL EXCEPTION [main]
Unity version     : 2020.3.41f1
Device model      : Xiaomi 220333QAG
Device fingerprint: Redmi/fog_global/fog:12/SKQ1.211103.001/V13.0.5.0.SGEMIXM:user/release-keys
Build Type        : Release
Scripting Backend : IL2CPP
ABI               : arm64-v8a
Strip Engine Code : true

Caused by: java.lang.IllegalArgumentException: parameter must be a descendant of this view
  at android.view.ViewGroup.offsetRectBetweenParentAndChild (ViewGroup.java:6335)
  at android.view.ViewGroup.offsetDescendantRectToMyCoords (ViewGroup.java:6264)
  at android.view.ViewRootImpl.scrollToRectOrFocus (ViewRootImpl.java:4984)
  at android.view.ViewRootImpl.draw (ViewRootImpl.java:4527)
  at android.view.ViewRootImpl.performDraw (ViewRootImpl.java:4370)
  at android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:3481)
  at android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:2272)
  at android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:8999)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:1160)
  at android.view.Choreographer.doCallbacks (Choreographer.java:950)
  at android.view.Choreographer.doFrame (Choreographer.java:879)
  at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:1142)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loopOnce (Looper.java:210)
  at android.os.Looper.loop (Looper.java:299)
  at android.app.ActivityThread.main (ActivityThread.java:8309)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:556)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1038)

**Comment by mhctseu** [comment]
@NVentimiglia Hi, could you confirm if this issue has been fixed within the latest release?

**Comment by shefich** [comment]
The issue still present in unity 2020.3.47 and 2021.3.23

**Comment by billyhct** [comment]
Hi All, we confirmed Version admob v8.1.0 still have this issue: offsetRectBetweenParentAndChild:

xception java.lang.Error: FATAL EXCEPTION [main]
Unity version     : 2020.3.33f1
Device model      : motorola moto e20
Device fingerprint: motorola/aruba/aruba:11/RON31.267-94/422c8:user/release-keys
Build Type        : Release
Scripting Backend : IL2CPP
ABI               : armeabi-v7a
Strip Engine Code : true

Caused by: java.lang.IllegalArgumentException: parameter must be a descendant of this view
  at android.view.ViewGroup.offsetRectBetweenParentAndChild (ViewGroup.java:6305)
  at android.view.ViewGroup.offsetDescendantRectToMyCoords (ViewGroup.java:6224)
  at android.view.ViewRootImpl.scrollToRectOrFocus (ViewRootImpl.java:4480)
  at android.view.ViewRootImpl.draw (ViewRootImpl.java:4046)
  at android.view.ViewRootImpl.performDraw (ViewRootImpl.java:3890)
  at android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:3152)
  at android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:2005)
  at android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:8236)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:972)
  at android.view.Choreographer.doCallbacks (Choreographer.java:796)
  at android.view.Choreographer.doFrame (Choreographer.java:731)
  at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:957)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:223)
  at android.app.ActivityThread.main (ActivityThread.java:7955)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:603)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:947)

**Comment by DevDreams12** [comment]
still getting crashes from users with these issue

**Comment by AndroidDeveloperLB** [comment]
Why is this closed? I can see it on this:

```
implementation 'com.google.android.gms:play-services-ads:23.0.0'
```

**Comment by Keyden** [comment]
8.2.0 not fix this problem
