### ISSUE TITLE
This feature requires ASM7

### ISSUE THREAD

**Issue by Zanoshky** [googleads/googleads-mobile-unity#2390]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.12f1
  * Google Mobile Ads Unity plugin version: 7.3.0
  * Platform: Unity Editor
  * Platform OS version: Android 12
  * Any specific devices issue occurs on: Windows 11
  * Mediation ad networks used, and their versions: N/A

#### Steps to reproduce:

When you try to build app **without** minification.
- Disabled R8
- Disabled Debug
- Disabled Release

Build fails with 

```
Caused by: java.lang.UnsupportedOperationException: This feature requires ASM7
```

If i enable R8 and Release and Debug, build works, ads works all fine.

**Comment by NVentimiglia** [comment]
@Zanoshky 

This sounds like a java build error related to mismatched runtimes. Can you step me through your build workflow? Please include all the javatime details such as your unity java version, your gradle java version, and what version of gradle you are using.

**Comment by SolanoMauri** [comment]
Error: Caused by: java.lang.UnsupportedOperationException: This feature requires ASM7
build workflow:

Unity 2021.3.11
(Unity Default) Gradle Version 6.1.1
(Unity Default) JDK version 8 (OpenJDK version 1.8)
Scripting  Backend: IL2CPP Net Standard 2.1
Target API level 31
Google Mobile Ads 7.3.0
OS: Windows 10
I had the same issue, 
1. Downloaded the pulgin
2. Went to preferences unclicked the library paths, click them again
3. Android Force Resolve 
4. Built and Error
I had enable Release, and R8, but that created a ClassNotFoundException error for google mobile ads functions when I ran on device and read the logs. I had to create a Proguard file to keep Google Ad classes.

Afterwards,

Unity 2021.3.11
(Unity Default) Gradle Version 6.1.1
(Unity Default) JDK version 8 (OpenJDK version 1.8)
Scripting  Backend: IL2CPP Net Standard 2.1
Target API level 32
Google Mobile Ads 7.3.0
OS: Windows 10
Afterwards, I decided to update SDK targets to a higher SDK API level support to API level 32 to test if the bug goes away with a newer SDK API target. Builds worked properly now without using Release, R8, or Proguard file, but it's still buggy.

The error does come back sometimes and I just build to alternate API levels between 31 and 32. For instance, if I get the error during a new session now I go to preferences unclicked the JDK.NDK,SDK, Gradle library paths, click them again,  and choose target SDK API level 31, I get a successful build, the error goes away and I switch back to target build I want of SDK API Level 32 and get no error for the rest of my session.

Not sure if this helps, but that was my experience this plugin version and has worked with two different projects. One using just google mobile ads 7.3.0 with network ad partners and one without network ad partners.

**Comment by Zanoshky** [comment]
@NVentimiglia 

Unity 2021.3.12
(Unity Default) Gradle Version 6.1.1
(Unity Default) JDK version 8 (OpenJDK version 1.8)

@SolanoMauri 

**Thank you so much for your input**, absolutely the same use case is for me.
Glad to hear i am not alone.

**Comment by HAL-JP** [comment]
Hello. I solved my problem this way.
Download the latest Gradle version here.
https://gradle.org/releases/

Place the unzipped Gradle file in the following location
/Applications/Unity/Hub/Editor/2021.3.12f1/PlaybackEngines/AndroidPlayer/Tools/gradle/
Please note that 2021.3.12f1 is the editor version and should be replaced with your own environment.

Next, open Unity and change the Gradle to be used.
From the top menu, select Unity > Preferences and open External Tools.

Uncheck the box marked "Gradle Installed with Unity (recommended)" and enter the path to the Gradle you just placed.

Now the Gradle used for building has been switched to a different version.
If there are no problems with the version, you should now be able to build Android.

**Comment by p0w1nd** [comment]
I'm having the same problem.

Unity 2021.3.12f1
Google Mobile Ads Unity plugin v7.3.0
Target API level 33

Thanks to @Zanoshky info, when I turn on those options in the Minify section:
R8: enabled
Debug: enabled
Release: enabled
... then it can build APK successfully.

**Comment by FlynnMacfarlane92** [comment]
Any update on this issue.. as in a concrete solution? Alternating between API 31 and 32 seems to work as @SolanoMauri noted.

**Comment by Zanoshky** [comment]
@p0w1nd 
Hey friend, i managed to find a solution for your ClassNotFound.

In the `project settings`, enable `custom proguard` and add this line to the file on path
`/Assets/Plugins/Android/proguard-user.txt`

Content:
```
-keep,includedescriptorclasses public class com.google.** { *; }
```

**Comment by p0w1nd** [comment]
Hey @Zanoshky 
Thanks for the info! My game has many 3rd party libs. After some time, I managed to fix the ClassNotFound errors. This is my proguard-user.txt file:

```
-keep class com.gameanalytics.sdk { *; }
-keep class com.gameanalytics.sdk.** { *; }
 
-keep class com.gameanalytics.sdk.GAPlatform { *; }
-keep class com.gameanalytics.sdk.GAPlatform.** { *; }
-keep class android.net.ConnectivityManager.** { *; }
-keep class com.google.android.instantapps.InstantApps { *; }
-keepclassmembers class com.google.android.instantapps.InstantApps { *; }

-keep public class com.facebook.**{ *; }
-keep public class com.facebook.internal.**{ *; }
````

The game is working well now.

**Comment by joaoborks** [comment]
In my case, I also use Unity Mobile Notifications Package and my builds are generated in a CI pipeline. This is what I needed to do to get it working:

1. Enable R8 minification _(I've only enabled it for Release)_ in Android Publishing Settings _(under Player Settings)_
2. Add custom proguard file:
    ```
    -keep,includedescriptorclasses public class com.google.** { *; }
    -keep public class com.unity.androidnotifications.** { *; }
    ```
    
I kept using API Level 31 for now. The latest Unity version (2022.2) has [R8 minification enabled by default](https://unity.com/releases/editor/whats-new/2022.2.0#APIChanges:~:text=Android%3A%20Obsoleted%3A%20PlayerSettings.Android.minifyWithR8%20is%20now%20obsolete%3A%20setting%20it%20now%20has%20no%20effect%20will%20always%20return%20true.) and it can't be turned off, so I guess this is the way to go from now on:

```
Android: Obsoleted: PlayerSettings.Android.minifyWithR8 is now obsolete: setting it now has no effect will always return true.
```

**Comment by MoHortus** [comment]
I had the same error after importing the plugin. So:

Unity 2021.3.15f1
Google Mobile Ads Unity plugin v7.3.1
Target API level 31
Windows 10

Firstly I tried to with new version of gradle as @HAL-JP described. Got some other error which led me to do:
Player Settings -> Publishing Settings, and check "Custom Base Gradle Template".
Just used the automatically generated content of the file for Custom Base Gradle Template.

Well then I had even more strange error.

So I decided to redo the changes. So to uncheck "Custom Base Gradle Template" and set back path for Gradle to:
...\Unity\2021.3.15f1\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\gradle

Then I got a build of package without an error.
(I also wanted to delete unzipped last gradle version, but could not... had to stop java services).

So I have no idea what is different, but it works now.

**Comment by linsir6** [comment]
I solve this issue in my local, 
replace distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-bin.zip to distributionUrl=https\://services.gradle.org/distributions/gradle-6.9.3-bin.zip
in gradle-wrapper.properties

**Comment by MoHortus** [comment]
> I solve this issue in my local, replace distributionUrl=https://services.gradle.org/distributions/gradle-6.1.1-bin.zip to distributionUrl=https://services.gradle.org/distributions/gradle-6.9.3-bin.zip in gradle-wrapper.properties

Works for me too,
1.) I make change in gradle-wrapper.properties under ...\MyProject\Library\Bee\Android\Prj\IL2CPP\Gradle\gradle\wrapper.
2.) Do Clean build...

But yeah I have to repeat that for every build as Clean build puts distrubitionUrl back to default value.

**Comment by khalidhex** [comment]
Just wanted to point out that changing gradle version did work but not with the latest release, so until v6.9.3 only

**Comment by CheeryLee** [comment]
> I solve this issue in my local, replace distributionUrl=https://services.gradle.org/distributions/gradle-6.1.1-bin.zip to distributionUrl=https://services.gradle.org/distributions/gradle-6.9.3-bin.zip in gradle-wrapper.properties

+1 to this. For me the error has appeared after UDP package has been imported. I updated Gradle to 6.9.3 and now it builds fine.

**Comment by Milium** [comment]
Increasing min API Level to Android 7 (API 24) worked for me.

**Comment by CraftedPvP** [comment]
> Increasing min API Level to Android 7 (API 24) worked for me.

I can confirm that this works. my build is able to compile

**Comment by AdnanGameDistrict** [comment]
> Increasing min API Level to Android 7 (API 24) worked for me.

It worked for me as well

**Comment by bartutiryakioglu** [comment]
I am still having this issue and neither increasing min api nor updating gradle solved my problem. Is there any other way to fix this? I am using Unity 2021.3.9f1 & AdMob 7.4.0

**Comment by mzgs** [comment]
> 

Just make a clean build it will works

**Comment by keksikq09** [comment]
> 



> > 
> 
> Just make a clean build it will works

Thx bro , u save my money

**Comment by zhigezuishuai** [comment]
> my unity version is 2020.3.33f1 without clean build , how to resolve

**Comment by tandy003** [comment]
Hey, I have been dealing with this issue for over a week now & tried everything to fix it. Tried clean builds, tried changing the minimum &  target API, different Admob & gradle versions. Nothing seems to work. 

I managed to randomly get a build working once, thought I fixed it but when I came back to the project a few days later the error just appeared again every time I tried building. This is happening in multiple projects. 

The only real fix I have found is removing Admob from my games completely. I'd rather not but at this point I might have to because nothing else is working. Any help or work around would be appreciated...

**Comment by Watcher3056** [comment]
+1, same issue.
Unity 2021.3.13f1

**Comment by unityDev01** [comment]
Same^ Hope issue will be solved soon. Game is ready but I can no t release with this error!!

**Comment by Watcher3056** [comment]
Hi again. Issue is easy to fix. You just need to:
- Download latets gradle version from: https://gradle.org/releases/
- Unzip gradle
- Open unity > Go to Preferences > External Tools > Gradle Path - set path to gradle you just downloaded
- Open Player Settings > Publishing. Toggle on "Custom Base Gradle Template"
- Open "Assets\Plugins\Android\baseProjectTemplate.gradle" with text editor
- Change the line that looks like classpath 'com.android.tools.build:gradle:yourversion' to classpath 'com.android.tools.build:gradle:4.2.0' or to any higher version

Now you can build.

**Comment by FlynnMacfarlane92** [comment]
Tried that solution above, however the issue persists. Doesn't fix it for me.

**Comment by zhigezuishuai** [comment]
use minify R8, then I resolved it,but it can cause some classNotFound error,so you must use proguard

**Comment by unityDev01** [comment]
> use minify R8, then I resolved it,but it can cause some classNotFound error,so you must use proguard

I try use r8 setting and it let me build but this breaks other games features when I go test. I don’t understand how to setup pro guard to fix because never used it before

**Comment by tandy003** [comment]
> **THE FIX**
> 
> Hi again. Issue is easy to fix. You just need to:
> 
> * Download latets gradle version from: https://gradle.org/releases/
> * Unzip gradle
> * Open unity > Go to Preferences > External Tools > Gradle Path - set path to gradle you just downloaded
> * Open Player Settings > Publishing. Toggle on "Custom Base Gradle Template"
> * Open "Assets\Plugins\Android\baseProjectTemplate.gradle" with text editor
> * Change the line that looks like classpath 'com.android.tools.build:gradle:yourversion' to classpath 'com.android.tools.build:gradle:4.2.0' or to any higher version
> 
> Now you can build.

This worked for me! I tried changing the gradle previously and I still had the error but setting custom base gradle and changing the class path too seemed to do the trick! I can build again. Thank you, I love you <3

**Comment by ProudPumPkin99** [comment]
Increasing min API Level to Android 6 (API 23) worked for me. and I reverted to min API Level to Android 5.1 (API 22) and was still working.

**Comment by zhigezuishuai** [comment]
> > use minify R8, then I resolved it,but it can cause some classNotFound error,so you must use proguard
> 
> I try use r8 setting and it let me build but this breaks other games features when I go test. I don’t understand how to setup pro guard to fix because never used it before

proguard-user.txt:
-renamesourcefileattribute SourceFile
-dontshrink
-dontoptimize
-dontobfuscate

**Comment by keksikq09** [comment]
> Hey, I have been dealing with this issue for over a week now & tried everything to fix it. Tried clean builds, tried changing the minimum & target API, different Admob & gradle versions. Nothing seems to work.
> 
> I managed to randomly get a build working once, thought I fixed it but when I came back to the project a few days later the error just appeared again every time I tried building. This is happening in multiple projects.
> 
> The only real fix I have found is removing Admob from my games completely. I'd rather not but at this point I might have to because nothing else is working. Any help or work around would be appreciated...

u can try change windows version , on win 10 pro my unity didnt work , in win 11 i didnt see any problems

**Comment by gagbaghdas** [comment]
> **THE FIX**
> 
> Hi again. Issue is easy to fix. You just need to:
> 
> * Download latets gradle version from: https://gradle.org/releases/
> * Unzip gradle
> * Open unity > Go to Preferences > External Tools > Gradle Path - set path to gradle you just downloaded
> * Open Player Settings > Publishing. Toggle on "Custom Base Gradle Template"
> * Open "Assets\Plugins\Android\baseProjectTemplate.gradle" with text editor
> * Change the line that looks like classpath 'com.android.tools.build:gradle:yourversion' to classpath 'com.android.tools.build:gradle:4.2.0' or to any higher version
> 
> Now you can build.

It's worked for em, thanks

**Comment by Chrissyee** [comment]
Hi, I believe the fix is much easier than what is currently being recommended. Go to project folder then \Library\Bee\Android.
Delete Android folder, try build. It worked for me and many others.

**Comment by Milium** [comment]
Why no one knows what causes this error? We just have some workarounds.

**Comment by MoHortus** [comment]
> **THE FIX**
> 
> Hi again. Issue is easy to fix. You just need to:
> 
> * Download latets gradle version from: https://gradle.org/releases/
> * Unzip gradle
> * Open unity > Go to Preferences > External Tools > Gradle Path - set path to gradle you just downloaded
> * Open Player Settings > Publishing. Toggle on "Custom Base Gradle Template"
> * Open "Assets\Plugins\Android\baseProjectTemplate.gradle" with text editor
> * Change the line that looks like classpath 'com.android.tools.build:gradle:yourversion' to classpath 'com.android.tools.build:gradle:4.2.0' or to any higher version
> 
> Now you can build.

Does not work for me.
But what works for me is to use gradle version 6.9.3. And not using "Custom Base Gradle Template".
So solution described in: https://forum.unity.com/threads/this-feature-requires-asm7.1360672/#post-8714193

Unity version: 2021.3.15f1
Google Mobile Ads Unity plugin version: 7.4.1
Platform: Unity Editor

**Comment by ahmedameen2** [comment]
Hi, Any update on this? I have tried all the above with no luck. Is that something related to Unity editor or Google ads? 
I am using unity 2021.3.12f and GoogleMobileAds-v7.4.1 
Started new empty project, no hope.

**Comment by ishahrukhktk** [comment]
hello everyone Im still stuck here...
im using admob 7.4.1
unity 2021.3.11f1 
gradle 6.9.1 

after building apk asm7 error comes but after checking true r8, debug, and release the build works but then no test ads on device.

i need help....

**Comment by nixonok** [comment]
Having this same annoying issue for months now, these workarounds, deleting folders, and force resolve before every single build is frustrating, i think google fired people working on this issue, can anyone help?

**Comment by Chrissyee** [comment]
Check your minimum supported Android API Level and make sure it's at least
7. That's an easy and permanent solution which resolved it for me, I hope
it works for you.

**Comment by s-k-georgiev** [comment]
For me I was using Android Studio project with kotlin and error was `This feature requires ASM7`
And the error was coming from local `module` that was using JAVA code, instead of Kotlin

The issue was solved by using:

```kotlin
plugins {
    id("org.jetbrains.kotlin.jvm")
    id("java-library")
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}
```

In the Gradle Kotlin DSL `*kts` file

**Comment by NightQnEarth** [comment]
> **THE FIX**
> 
> Hi again. Issue is easy to fix. You just need to:
> 
> * Download latets gradle version from: https://gradle.org/releases/
> * Unzip gradle
> * Open unity > Go to Preferences > External Tools > Gradle Path - set path to gradle you just downloaded
> * Open Player Settings > Publishing. Toggle on "Custom Base Gradle Template"
> * Open "Assets\Plugins\Android\baseProjectTemplate.gradle" with text editor
> * Change the line that looks like classpath 'com.android.tools.build:gradle:yourversion' to classpath 'com.android.tools.build:gradle:4.2.0' or to any higher version
> 
> Now you can build.

It works for me, thanks bro!

**Comment by elfadili-ae** [comment]
Deleting resolved libraries before building also works.

**Comment by Agares1024** [comment]
I solved this problem after modifying the "com.android.tools.build:gradle:4.2.1" version number in file "baseProjectTemplate" to be consistent with PackagesManager=>Advertisement :-P

**Comment by Agares1024** [comment]
I solved this problem after modifying the "com.android.tools.build:gradle:4.2.1" version number in file "baseProjectTemplate" to be consistent with PackagesManager=>Advertisement
Unity 2020.3.48
Gradle Version 6.9.3
Target API level 33
Scripting Backend:Mono .Net 4.x

**Comment by Agares1024** [comment]
I solved this problem after modifying the "com.android.tools.build:gradle:4.2.1" version number in file "baseProjectTemplate" to be consistent with PackagesManager=>Advertisement
Unity 2020.3.48
Gradle Version 6.9.3
Target API level 33
Scripting Backend:Mono .Net 4.x

**Comment by anhTuan2703** [comment]
> Hey @Zanoshky Thanks for the info! My game has many 3rd party libs. After some time, I managed to fix the ClassNotFound errors. This is my proguard-user.txt file:
> 
> ```
> -keep class com.gameanalytics.sdk { *; }
> -keep class com.gameanalytics.sdk.** { *; }
>  
> -keep class com.gameanalytics.sdk.GAPlatform { *; }
> -keep class com.gameanalytics.sdk.GAPlatform.** { *; }
> -keep class android.net.ConnectivityManager.** { *; }
> -keep class com.google.android.instantapps.InstantApps { *; }
> -keepclassmembers class com.google.android.instantapps.InstantApps { *; }
> 
> -keep public class com.facebook.**{ *; }
> -keep public class com.facebook.internal.**{ *; }
> ```
> 
> The game is working well now.

hey, how can you list all your 3rd libs
