### ISSUE TITLE
I get a message in logcat about using deprecated sdk, but i used last version of admob unity plugin

### ISSUE THREAD

**Issue by mahdijj** [googleads/googleads-mobile-unity#2957]
* Unity version: 2021.3.12
  * Google Mobile Ads Unity plugin version: 8.5.2
  * Platform: Android
  * Platform OS version: Android 8

I get this message after initialize in android logcat after running game in android device:

Received log message: <Google:HTML> You are currently using version 232400999.231700000.1 of the SDK, which is out of date. Please consider updating your SDK to the most recent SDK version to get the latest features and bug fixes. The latest SDK can be installed from https://googlemobileadssdk.page.link/android-install-instructions. More information about the SDK deprecation schedule is available at https://developers.google.com/admob/android/deprecation.

I used last unity plugin and i don't know why i get this message.

**Comment by NVentimiglia** [comment]
Hi @mahdijj 

The Unity plugin is a c# wrapper around a native level sdk imported into the plugin folder. This process is managed by the external dependency manager.

My guess is we are importing an old version of the SDK there, can you please verify that the `ependendencies.xml` file has the latest version of the SDK listedn and run the external dependency manager (Assets > External Dependency Manager > Android > Force Resolve) and verify that you are on the latest. 

Alternatively, you can delete and reimport the plugin. This should fix the problem in the case where an update did not update the dependencies xml file correctly.

**Comment by omml** [comment]
Hello @NVentimiglia ,

I'm having the same issue. Do you mean the GoogleMobileAdsDependencies.xml file? I have deleted the plug in and installed it again and still get the same problem.

Thank you

**Comment by mahdijj** [comment]
I think this problem is in a new game and problem is solved after several download and run of game by players

**Comment by NVentimiglia** [comment]
@omml Yes I mean the `GoogleMobileAdsDependencies.xml` file.

If you can share with me the version of the Android SDK you are using from this file as well as the exact error log I will take another look.
