### ISSUE TITLE
AdMob 11.10.0.0 and AppLovin 13.0.0 not working on iOS

### ISSUE THREAD

**Issue by NecroMacro** [googleads/googleads-mobile-unity#3641]
* Unity version: 2023.3.18
  * Google Mobile Ads Unity plugin version: 11.10.0.0
  * Platform: iOS
  * Mediation ad networks used, and their versions: AppLovin 13.0.0

```
[!] CocoaPods could not find compatible versions for pod "Google-Mobile-Ads-SDK":
  In Podfile:
    AppLovinMediationGoogleAdapter (= 11.10.0.0) was resolved to 11.10.0.0, which depends on
      Google-Mobile-Ads-SDK (= 11.10.0)
    Google-Mobile-Ads-SDK (= 11.5.0.0)
Specs satisfying the `Google-Mobile-Ads-SDK (= 11.5.0.0), Google-Mobile-Ads-SDK (= 11.10.0)` dependency were found, but they required a higher minimum deployment target.
```

**Comment by NecroMacro** [comment]
Allversions after 11.5.0.0 don't work (11.6, 11.7...)

**Comment by NVentimiglia** [comment]
AppLovin requires that `Link frameworks satically` is uncheck in the `Menu > Assets > External Dependency Manager > iOS resolver > Settings` menu.

![image](https://github.com/user-attachments/assets/181bc45c-8bcd-462a-a15c-45a0e6db35bc)

**Comment by NudeNULL** [comment]
Disabling that checkmark doesn't help, same issue, can't build.

[!] CocoaPods could not find compatible versions for pod "Google-Mobile-Ads-SDK":
  In Podfile:
    AppLovinMediationGoogleAdManagerAdapter (= 11.12.0.0) was resolved to 11.12.0.0, which depends on
      Google-Mobile-Ads-SDK (= 11.12.0)

    Google-Mobile-Ads-SDK (~> 11.7.0)

**Comment by NudeNULL** [comment]
If I force the Google-Mobile-Ads-SDK version in dependencies file to 11.12.0.0 then during the xcode build the linker fails

I am using Google Mobile Ads SDK 9.2.0, I don't think upgrading to 9.3.0 will help.

**Comment by mixadze1** [comment]
on 9.3.0 same problem, any solutions?

[!] CocoaPods could not find compatible versions for pod "Google-Mobile-Ads-SDK":
  In Podfile:
    AppLovinMediationGoogleAdapter (= 11.12.0.0) was resolved to 11.12.0.0, which depends on
      Google-Mobile-Ads-SDK (= 11.12.0)

    Google-Mobile-Ads-SDK (~> 11.11.0)

**Comment by Fraccas** [comment]
I was able to get Google Mobile Ads Unity Plugin v9.4.0 working on iOS with the AppLovin Mediation Adapter by updating the AppLovin Adapter Plugin to version 8.0.3

https://developers.google.com/admob/unity/mediation/applovin#applovin-unity-mediation-plugin-changelog

Podfile
```
source 'https://cdn.cocoapods.org/'
source 'https://github.com/CocoaPods/Specs'

platform :ios, '12.0'

target 'UnityFramework' do
  pod 'GoogleMobileAdsMediationAppLovin', '13.0.1.0'
  pod 'Google-Mobile-Ads-SDK', '~> 11.12.0'
  pod 'GoogleUserMessagingPlatform', '2.7.0'
end
target 'Unity-iPhone' do
end
use_frameworks!

```

**Comment by Davidnovarro** [comment]
> We have published a new solution to this issue: https://developers.google.com/admob/unity/ios-mediation-errors

Why isn’t this value added by default? I installed the adapter using the Package Manager, so how am I supposed to change the immutable file value? And why should I have to? It should just work out of the box. If you already know how to fix the issue, why not include the fix in the package?

![Image](https://github.com/user-attachments/assets/e8e35328-2122-4725-a089-86822d11a989)

**Comment by vinkini** [comment]
We have added it to the AppLovin, InMobi and Maio packages and they will be available in the upcoming release. This document was published as a quick fix to mitigate the issue in the meantime. Since the steps involve creating a new file under Assets, you should not be facing any issues related to immutability of contents under packages.

**Comment by 9domino9** [comment]
Hi, I'm having a similar problem with a non-functioning build on iOS. I also tried updating admob to the latest version (v10.1.0.) with the iOS SDK dependency version (12.3.0.), but I still have a conflict with the intermediate version of the admob applovin. 

"Dependency analysis
[!] CocoaPods did not find a compatible version for under "Google-Mobile-Ads-SDK":
 In the file under:
 AppLovinMediationGoogleAdapter (= 12.4.0.1) has been resolved to 12.4.0.1, which depends on
 Google-Mobile-Ads-SDK (= 12.4.0)

    Google-Mobile-Ads-SDK (~> 12.3.0)
Specifications were found to satisfy the dependencies of Google-Mobile-Ads-SDK (~> 12.3.0), Google-Mobile-Ads-SDK (= 12.4.0), but required a higher minimum deployment target."

I also tried the advice you posted in this thread, but unfortunately nothing helped me. I also tried downgrading the applovin admob mediation version to 12.3.0 but that didn't help either. Please does anyone have any more up to date information that might help me ? Thank you in advance.

**Comment by NVentimiglia** [comment]
This should be fixed now in the latest version.
