### ISSUE TITLE
Ad close button is hidden behind navigation menu

### ISSUE THREAD

**Issue by programmermattsrum** [googleads/googleads-mobile-unity#3764]
### [REQUIRED] Step 1: Describe your environment

  * Unity version:  2022.3.6.61f
  * Google Mobile Ads Unity plugin version: 10.0.0
  * Plugin installation method: unitypackage import
  * Platform: Android
  * Platform OS version: Android 15
  * Any specific devices issue occurs on: pixel 8 pro and pixel 6
  * Mediation ad networks used, and their versions:  ironsource 3.1.0

#### Steps to reproduce:

What happened? How can we make the problem occur?
When an interstitial Ad or Reward Ad is shown, the close button is not visable and can't be clicked.

Also, just noting that the navigation menu only shows when an ad appears not during game play.

During game play
![Image](https://github.com/user-attachments/assets/22936e09-2af9-4918-af9d-9ea4c2a9c89b)

Interstial Ad Examples
![Image](https://github.com/user-attachments/assets/daf3eff7-c564-475b-aad4-e74987074e8a)
![Image](https://github.com/user-attachments/assets/2b81638c-8b69-4ee3-a881-e7d59104fa69)
![Image](https://github.com/user-attachments/assets/af75f3fe-9b38-4bb5-8dfb-838c2cd72b5e)

Reward Ad Examples
![Image](https://github.com/user-attachments/assets/8cca06a4-f14e-4bbe-a43b-65ddba7845a9)
![Image](https://github.com/user-attachments/assets/b1a3f29a-b959-4d09-9229-35afcd93173a)

Issue caused update to google play to be rejected because of the Families Policy
![Image](https://github.com/user-attachments/assets/eef915a4-a946-4a1e-ab6e-dde6e2ba8352)

I've been using this plugin since 2019 and never had this issue until I updated to version 10.0.0

@vinkini please help me understand how to fix this?

Current version in the Google Play Store uses version 9.1.0 before I updated to 10.0.0
![Image](https://github.com/user-attachments/assets/e6be5034-4904-46a9-9556-f2f5e27e589d)

Thanks,
Matt

**Comment by programmermattsrum** [comment]
@takazawa-gg @dcosmin-97 @RaadGames Are any of you having the same issue?

@NVentimiglia Have you seen this issue?

**Comment by RaadGames** [comment]
Hey, no i don't have seen this problem before ,maybe related to the phone you tested the game on , if you wanna test it on our game and see if happens on same device, https://play.google.com/store/apps/details?id=com.raadgames.DriftMax

**Comment by programmermattsrum** [comment]
@RaadGames Played your game a little bit the banner ads are not looking right on the pixel 8 pro.  I also noticed that when the interstial ads showed the navigation menu did not show on your game.  Are you hiding it with code?

![Image](https://github.com/user-attachments/assets/96c89f65-199a-4d50-b9f8-bb08cecb2a96)
![Image](https://github.com/user-attachments/assets/5ab13f6f-ceeb-4540-8e0a-86a4b0346f77)

**Comment by programmermattsrum** [comment]
Also, I have the navigation hidden but google mobile ads shows the navigation?  Shouldn't it be hidden?

![Image](https://github.com/user-attachments/assets/0da3b395-a946-4b54-be5f-34c97d54914d)

**Comment by programmermattsrum** [comment]
@joshuajplagonera Any ideas on this issue on how to resolve it?

**Comment by RaadGames** [comment]
no i dont hide anything , i just show the ad normlay , but yeah the banner we have problem with it it's always show wrong positon it's a bug :( 

have you test it on Unity 6? 

![Image](https://github.com/user-attachments/assets/b096be60-18da-4bcf-b1f7-ca24c3f0e805)

**Comment by programmermattsrum** [comment]
@RaadGames Tried Unity 6 tonight but same result.

**Comment by vinkini** [comment]
Hi @programmermattsrum,
We looked into the issue. While I was unable to replicate having the close button behind the 3 button navigation, I do feel we should not be popping up the navigation and status bars while showing full screen ads. The GMA Android SDK has a setting that enables us to disable nav and status bars during ad show. We have added the change and will be available in the upcoming release this week. Thanks for bringing this to our attention.

**Comment by programmermattsrum** [comment]
@vinkini ,
When will the release come out?

**Comment by SeriouslyRichMan** [comment]
Same problem, Unity 6 (6000.0.43f1), admob 10.0.0

**Comment by vinkini** [comment]
We have just released the v10.1.0 SDK that should address this issue. Can you please try with that and let us know if it works for you?

**Comment by programmermattsrum** [comment]
@vinkini ,

I will test it tonight and let you know.

Thanks for the help,
Matt

**Comment by programmermattsrum** [comment]
@vinkini,

Good news the update fixed the issue here is a few screenshots for you to see.

![Image](https://github.com/user-attachments/assets/8d3014c3-0a24-4a59-9cc4-d93164720a82)
![Image](https://github.com/user-attachments/assets/81a12140-c088-48c6-b7cd-b5f5321b6736)
![Image](https://github.com/user-attachments/assets/2bbe0aad-4ac6-4082-b6ac-73c909882ae1)

**Comment by vinkini** [comment]
Thanks @programmermattsrum for trying it out quickly! Glad it worked!

**Comment by SeriouslyRichMan** [comment]
I still have a problem, Unity 6 (6000.0.43f1), admob 10.1.0

![Image](https://github.com/user-attachments/assets/9abf8d7b-362f-439f-aeaa-a8c9158fbc0c)

![Image](https://github.com/user-attachments/assets/70ca5f10-ee15-45e7-9ed9-dd407f3049d1)

**Comment by vinkini** [comment]
Hey @SeriouslyRichMan. The fix we pushed turned on immersive mode during full screen ads. This should cause the SDK to hide the navigation and status bars during ads. Can you check if this is more of a cache issue. 
1) Delete all existing Google Mobile Ads files, most of all the googlemobileads-unity.aar under Assets/Plugins/Android (If you installed it using Package Manager, try uninstalling and reinstalling the package).
2) Perform a Clean Build. 

![Image](https://github.com/user-attachments/assets/c866c8f0-1560-4149-ab94-7d0bfd1a85e2)

**Comment by SeriouslyRichMan** [comment]
Hi vinkini. Thanks for your help, this problem is solved, but my game still crashes after showing ads https://github.com/googleads/googleads-mobile-unity/issues/3761
