### ISSUE TITLE
RewardedAd OnAdOpening 、OnAdClosed and OnUserEarnedReward calllbacks are not called

### ISSUE THREAD

**Issue by qq464418017** [googleads/googleads-mobile-unity#976]
// Called when an ad request has successfully loaded.
	    this.rewardedAd.OnAdLoaded += HandleRewardedAdLoaded;
	    // Called when an ad request failed to load.
	    this.rewardedAd.OnAdFailedToLoad += HandleRewardedAdFailedToLoad;
	    // Called when an ad is shown.
	    this.rewardedAd.OnAdOpening += HandleRewardedAdOpening;
	    // Called when an ad request failed to show.
	    this.rewardedAd.OnAdFailedToShow += HandleRewardedAdFailedToShow;
	    // Called when the user should be rewarded for interacting with the ad.
	    this.rewardedAd.OnUserEarnedReward += HandleUserEarnedReward;
	    // Called when the ad is closed.
	    this.rewardedAd.OnAdClosed += HandleRewardedAdClosed;

all callbackes are not called

**Comment by stowy** [comment]
Please can you confirm which device, platform, platform version and plugin
version you are using? And are you using mediation?

**Comment by AliahmadDev** [comment]
Hi, i am also facing the same issue from last 2 months, in my case i am currently using admob unity sdk 3.18.3 and no mediation is implemented. Unity Editor version is 2018.4.8 LTS and android versions facing this problem are 5.0, 7.0, 8.1, 9.0 (i have seen this on these version and i think it is irrespective of the android versions)

**Comment by stowy** [comment]
Have you tried the Helloworld sample app? I haven't seen this issue in
testing.

**Comment by AliahmadDev** [comment]
Hi, sorry for the late reply here as i was not at office at weekend.
I have tried the HelloWorld Sample App, that works. But when i write some lines of code in the handler of rewarded video (where the user is to be rewarded) sometimes it works and sometimes it does not. In previous versions of admob sdk i noticed the crash when we call handler but in this current release it is fixed and app does not crash at handler.
Current problem that i have noticed that;
i- rewardedvideo.isloaded() does not returns the right bool, means sometimes it says true (means the rewarded video is available) but when i try to show the video by calling .show() method the video does not starts because of non availability.
ii- second issue i have notices that the handler (of video shown to user with success results) does not executes some lines of code except the simplest things, like it just changes the bool value, or can print a line in editor, then i have to check that boolean in update function for its value (whether its changed or not) than i can perform my functionality.
I am looking forward to you for the solutions of these issues, i hope you'll get my problem :)

**Comment by nyms0390** [comment]
Facing the same issue. OnUserEarnedReward is sometimes not called for unknown reason.

**Comment by essoperagma** [comment]
As discussed in [this issue](https://github.com/googleads/googleads-mobile-unity/issues/1059), RewardedAd callbacks are not always triggered from the main thread. Changing the value of primitives should be fine, but as soon as you do something bigger you will corrupt your memory. Monobehaviour.print works, because it is [most likely](http://answers.unity.com/answers/1103683/view.html) thread safe. You need to make sure that your actions are invoked from the main thread.

I am already using [UniRx](https://github.com/neuecc/UniRx) in my project, so I fixed it like this:

```
public void HandleRewardBasedVideoClosed(object sender, EventArgs args)
{
	Scheduler.MainThread.Schedule(() =>
	{
		MonoBehaviour.print("HandleRewardBasedVideoClosed event received");
		// Do whatever you want to do here
	});
}
```

If you don't want to import a plugin that big into your project, there is also [UnityMainThreadDispatcher](https://github.com/PimDeWitte/UnityMainThreadDispatcher) (I haven't used this. I don't know if it works.)

**Comment by padwekar** [comment]
Still facing the same issue. All other callbacks (onRewardedAdLoaded,onRewardedAdOpened & onRewardedAdClosed) are getting called except onUserEarnedReward.

**Comment by stowy** [comment]
Can you provide repro steps for not receiving `onUserEarnedReward` callback? In order to send private information, I would recommend posting on our developer forum - they will reply promptly and help debug your issue.

With regards to posting events to Unity main loop, you can also use [MobileAdsEventExecutor](https://github.com/googleads/googleads-mobile-unity/blob/master/source/plugin/Assets/GoogleMobileAds/Common/MobileAdsEventExecutor.cs) methods with `ExecuteInUpdate` or `InvokeInUpdate` functions.

**Comment by padwekar** [comment]
@stowy Thanks. It's resolved now. The problem was the use of the wrong combination of real Admob account Id with test Ad Id. After replacing the real Admob account Id with the test account id in manifest fixed the issue. In Short:
Real Admob Account Id + Test Reward Ad id - Caused the callback issue.
Test Admob Account Id + Test Reward Ad id - Fixed The Issue.

**Comment by JonathanDotCel** [comment]
Been getting this for a while now, IOS and Android, Unity 2018 to 2019.4
We've been point blank unable to get OnAdOpening to happen which makes it a little difficult to predict how much UI to set aside for smart banners and the likes.

TBH using any of the google plugins/libs/resolver with unity has been such a directionless, buggy mess that this minor just got swept under the rug, but yep... here we are in a fresh install of Catalina, fresh plugins, fresh IOS, everything reinstalled and no callbacks, even when throwing a Debug.Log() (thread safe) on the BannerClient.

Reward ads are their own other special flavour of unreliable, but one thing at atie.

**Comment by dgogolev** [comment]
Hi, I have the same issue:  All other callbacks (onRewardedAdLoaded, onRewardedAdOpened & onRewardedAdClosed) are getting called except onUserEarnedReward. Did you managed this problem somehow?
